### ISSUE TITLE
server and client crash v1.6

### ISSUE THREAD

**Issue by sjz123321** [snail007/shadowtunnel#13]
Hello,snail!
I was runing shadowtunnel in debug mode.when I want to quit it, it occurs.
Both Server and Client have this problem,here is the output log:

2019/03/25 22:03:51.853881 st.go:705: clean handler crashed, err :
goroutine 8 [running]:
runtime/debug.Stack(0xc0420b7df0, 0x7d9860, 0xa81570)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/shadowtunnel/core.cleanup.func1.1()
        /home/pengmeng/go/src/github.com/snail007/shadowtunnel/core/st.go:434 +0x4f
panic(0x7d9860, 0xa81570)
        /usr/local/go/src/runtime/panic.go:502 +0x237
time.(*Ticker).Stop(0x0)
        /usr/local/go/src/time/tick.go:46 +0x29
github.com/snail007/shadowtunnel/core.Stop()
        /home/pengmeng/go/src/github.com/snail007/shadowtunnel/core/st.go:447 +0x6c
github.com/snail007/shadowtunnel/core.cleanup.func1(0xc04204c300, 0xc042055800)
        /home/pengmeng/go/src/github.com/snail007/shadowtunnel/core/st.go:438 +0x5b
created by github.com/snail007/shadowtunnel/core.cleanup
        /home/pengmeng/go/src/github.com/snail007/shadowtunnel/core/st.go:431 +0x154

**Comment by sjz123321** [comment]
solved
